Takonasu/bugfix#1,2
twin-te/donation-service pull request #3
Opened 2022-05-01 04:32 UTC by takonasu

#1 #2 のバグfix
testは通るのだけど、ApiGateway経由で試せてないです

2022-05-02 05:05 UTC, SIY1121 requested changes
お疲れです 🙏 

gRPC(protobuf)では一般的にprotoファイルの破壊的な変更は行わない事になってます。
理由としてはサーバー（今回はDonationService）とクライアント（今回はApiGateway）を同時に更新しないと正しく動作しなくなるから。
参考：https://docs.microsoft.com/ja-jp/aspnet/core/grpc/versioning?view=aspnetcore-6.0
stringからintへの型変更は破壊的変更なので、もしやりたい場合は

```proto
message Payment {
...
  reserved 5; // 5番はもう使わない
  int32 created = 6;
}
```

のようにすると、シリアライズのエラーは起こらなくなる。
ただ型を変更すると上記の手間が発生するのと同時に、openapi-specの型も変更する必要がある。
調べたら `dayjs.unix()` なるものがあるっぽいのでそこだけ変えれば良いかなと。

2022-05-02 05:05 UTC, SIY1121 commented on protos/DonationService.proto
> +  int32 created = 5;
protoファイルに対する破壊的な変更は好ましくない

2022-05-02 05:05 UTC, SIY1121 commented on protos/DonationService.proto
> +  int32 created = 4;
こちらも同様

2022-05-03 01:33 UTC, takonasu commented
@SIY1121 お疲れ様です、レビューありがとう！
なるほど、確かにapi-gatewayへの変更が必要になるので良くないね・・・

修正したので確認をお願いします

2022-05-03 16:02 UTC, SIY1121 approved these changes
感謝 🙏

2022-05-04 01:23 UTC, merged